//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megastore
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public customer()
        {
            this.shipments = new HashSet<shipment>();
        }
    
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string customer_address { get; set; }
        public string customer_email { get; set; }
        public string customer_password { get; set; }
    
        public virtual ICollection<shipment> shipments { get; set; }
    }
}
