//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megastore
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public product()
        {
            this.shipment_details = new HashSet<shipment_details>();
        }
    
        public int product_id { get; set; }
        public string product_name { get; set; }
        public string product_description { get; set; }
        public int product_type_idproduct_type { get; set; }
        public string unit { get; set; }
        public Nullable<decimal> price_per_unit { get; set; }
        public string image_url { get; set; }
        public int categories_catogories_id { get; set; }
    
        public virtual category category { get; set; }
        public virtual product_type product_type { get; set; }
        public virtual ICollection<shipment_details> shipment_details { get; set; }
        public virtual stock stock { get; set; }
    }
}
