//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megastore
{
    using System;
    using System.Collections.Generic;
    
    public partial class shipment_details
    {
        public int shipment_details_id { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public int product_product_id { get; set; }
        public int shipment_shipment_id { get; set; }
    
        public virtual product product { get; set; }
        public virtual shipment shipment { get; set; }
    }
}
