//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megastore
{
    using System;
    using System.Collections.Generic;
    
    public partial class shipment
    {
        public shipment()
        {
            this.shipment_details = new HashSet<shipment_details>();
        }
    
        public int shipment_id { get; set; }
        public Nullable<System.DateTime> time_created { get; set; }
        public string shipping_address { get; set; }
        public string billing_address { get; set; }
        public Nullable<decimal> delivery_cost { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<decimal> final_price { get; set; }
        public string customer_customer_email { get; set; }
        public int payment_type_payment_type_id { get; set; }
        public int shipment_type_sipment_type_id { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual payment_type payment_type { get; set; }
        public virtual ICollection<shipment_details> shipment_details { get; set; }
        public virtual shipment_type shipment_type { get; set; }
    }
}
