//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Megastore
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock
    {
        public int product_id { get; set; }
        public Nullable<decimal> in_stock { get; set; }
        public Nullable<System.DateTime> last_update_time { get; set; }
    
        public virtual product product { get; set; }
    }
}
